### ISSUE TITLE
Delete old synced folder before a new sync

### ISSUE THREAD

**Issue by valentinocossar** [beliven-it/hssh#24]
Because a folder could have old files inside, an improvement could be deleting synced folder before redownloading it. This fixes a current issue with the new multi-provider function and the new file naming convention (eg. test.gitlab) that causes duplicated files: the older ones (pre multi-provider) and the new ones (post multi-provider) that are equal.

**Comment by CasvalDOT** [comment]
I changed the logic slightly ...
Instead of deleting the folder, I'm going to delete only the obsolete files, that is, all the other files that have not just been downloaded and created. I've also changed the output of the sync command; I've highlighted the provider name and the action performed (created, deleted) in the same way as the output of init command

![screenshot_1619280143](https://user-images.githubusercontent.com/8190931/115964986-8c801580-a516-11eb-9bc6-cff9f8bd188a.png)

**Comment by valentinocossar** [comment]
@CasvalDOT lgtm!
