### ISSUE TITLE
Add multi-provider logic

### ISSUE THREAD

**Issue by valentinocossar** [beliven-it/hssh#4]
Add multi-provider logic with support for more than one provider at the same time, this allows to pull hosts from more than one source.

Tip: pay attention to file conflicts inside `config.hssh.d` folder, prepend config files name with `provider.file-name` or add a provider sub folder logic.

**Comment by CasvalDOT** [comment]
@valentinocossar, I've add the possibility to handle a list of providers. 

In the configuration file (config.yml) you can now declare a property called `providers` that accept
a list of providers connections. 

```yml
providers:
  - "gitlab://<TOKEN>:/<PROJECT_ID>@<FOLDER>"
  - "github://<TOKEN>:/<PROJECT_ID>@<FOLDER>"
```

When you use the command `hssh s`, the system fetch the files from both providers and create the files adding the provider name at the end of the file name.
I decided to add the name to the end instead of at the beginning because it was easier to implement and require less changes

```bash
personal.github
projects.gitlab
...
```

**NOTES**

You can then use both the **provider** property along with the **providers** property. The system will then take a unique list of providers.
This choice allows users not to have to change the configuration file to the next update. 
Maybe with the release 2.0.0 we could remove the single provider in favor only a list.

You can test this feature trying to configure the connection string for github for my private repository `dotnet`.
Some params below:

```
PROJECT_ID = "/CasvalDOT/dotnet"
FOLDER = "connections"
```

**Comment by valentinocossar** [comment]
@CasvalDOT wow! I have a question: when you run the `init` command or when you fresh install the CLI, the auto-created config file, is created with the new or the old template?

**Comment by CasvalDOT** [comment]
> valentinocossar (Member) • 8h • Newest comment
  @CasvalDOT wow! I have a question: when you run the  init  command or when
  you fresh install the CLI, the auto-created config file, is created with the
  new or the old template?

The new template!!

**Comment by valentinocossar** [comment]
Ok, thank you!
