### ISSUE TITLE
Not all commands auto-create the configuration file on the first run

### ISSUE THREAD

**Issue by valentinocossar** [beliven-it/hssh#7]
Possible bug to test: not all commands auto-create the configuration file on the first run.

**Comment by CasvalDOT** [comment]
I've tried to reproduce the issue. 
1. I've deleted **config.yml** and **config.hssh.d**  
2. Launch the command **hssh c**

But the script work as expected. Below the output:

```
Created missing /home/casval/.config/hssh/config.yml file!
Before starting to use hssh edit the newly created configuration file.
```

Launching again the command, the script return the following error:
```
The host folder is empty.
Running the first sync...
Cannot get files from provider: {"message":"401 Unauthorized"}
exit status 1
```

But the behavior seems correct, due to configuration file is not configured yet

@valentinocossar can you try too?

**Comment by valentinocossar** [comment]
@CasvalDOT I confirm that I can't reproduce the reported issue and everything works as expected.
